LOAD DATA LOCAL INFILE "/Users/katieovens/Downloads/Licensed_Pets.csv"
INTO TABLE licensed_pets
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(@DATE, COMMUNITY_CODE, COMMUNITY_NAME, ANIMAL_TYPE, LICENSE_VOLUME, ROW_ID, @POINT)
SET DATE = STR_TO_DATE(@DATE, '%m/%d/%Y %h:%i:%s %p'), POINT = ST_PointFromText(@POINT);
